<?php

use Illuminate\Database\Seeder;
use App\post;

class postTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $pots = [
          [
            'author_id' => '1',
            'title' => 'Obesidad y sobrepeso',
            'excerpt' => 'El sobrepeso y la obesidad se definen como una acumulación anormal o excesiva de grasa que puede ser perjudicial para la salud.',
            'body' => '<div style="box-sizing: border-box; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;">
<p style="box-sizing: border-box;"><span style="box-sizing: border-box; font-size: 33px;">Datos y cifras<br style="box-sizing: border-box;" /><br style="box-sizing: border-box;" /></span></p>
</div>
<ul style="box-sizing: border-box; float: inherit; padding-left: 20px; width: 812.219px; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;">
<li style="box-sizing: border-box;">
<p style="box-sizing: border-box;">Desde 1975, la obesidad se ha casi triplicado en todo el mundo.</p>
</li>
<li style="box-sizing: border-box;">
<p style="box-sizing: border-box;">En 2016, m&aacute;s de 1900 millones de adultos de 18 o m&aacute;s a&ntilde;os ten&iacute;an sobrepeso, de los cuales, m&aacute;s de 650 millones eran obesos.</p>
</li>
<li style="box-sizing: border-box;">
<p style="box-sizing: border-box;">En 2016, el 39% de las personas adultas de 18 o m&aacute;s a&ntilde;os ten&iacute;an sobrepeso, y el 13% eran obesas.</p>
</li>
<li style="box-sizing: border-box;">
<p style="box-sizing: border-box;">La mayor&iacute;a de la poblaci&oacute;n mundial vive en pa&iacute;ses donde el sobrepeso y la obesidad se cobran m&aacute;s vidas de personas que la insuficiencia ponderal.</p>
</li>
<li style="box-sizing: border-box;">
<p style="box-sizing: border-box;">En 2016, 41 millones de ni&ntilde;os menores de cinco a&ntilde;os ten&iacute;an sobrepeso o eran obesos.</p>
</li>
<li style="box-sizing: border-box;">
<p style="box-sizing: border-box;">En 2016 hab&iacute;a m&aacute;s de 340 millones de ni&ntilde;os y adolescentes (de 5 a 19 a&ntilde;os) con sobrepeso u obesidad.</p>
</li>
<li style="box-sizing: border-box;">
<p style="box-sizing: border-box;">La obesidad puede prevenirse.</p>
</li>
</ul>
<h2 class="section_head1" style="box-sizing: border-box; font-variant-numeric: normal; font-variant-east-asian: normal; font-weight: normal; font-stretch: normal; font-size: 37px; line-height: 47px; font-family: Arial, Helvetica, sans-serif; color: #3c4245;">&iquest;Qu&eacute; son el sobrepeso y la obesidad?</h2>
<p style="box-sizing: border-box; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;"><span style="box-sizing: border-box;">El sobrepeso y la obesidad se definen como una acumulaci&oacute;n anormal o excesiva de grasa que puede ser perjudicial para la salud.</span></p>
<p style="box-sizing: border-box; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;"><span style="box-sizing: border-box;">El &iacute;ndice de masa corporal (IMC) es un indicador simple de la relaci&oacute;n entre el peso y la talla que se utiliza frecuentemente para identificar el sobrepeso y la obesidad en los adultos. Se calcula dividiendo el peso de una persona en kilos por el cuadrado de su talla en metros (kg/m<sup style="box-sizing: border-box;">2</sup>).</span></p>
<p style="box-sizing: border-box; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;">&nbsp;</p>
<h3 class="section_head2" style="box-sizing: border-box; font-variant-numeric: normal; font-variant-east-asian: normal; font-weight: normal; font-stretch: normal; font-size: 30px; line-height: 40px; font-family: Arial, Helvetica, sans-serif; color: #3c4245;">Adultos</h3>
<p style="box-sizing: border-box; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;"><span style="box-sizing: border-box;">En el caso de los adultos, la OMS define el sobrepeso y la obesidad como se indica a continuaci&oacute;n:</span></p>
<ul style="box-sizing: border-box; float: inherit; padding-left: 20px; width: 812.219px; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;">
<li style="box-sizing: border-box;">sobrepeso: IMC igual o superior a 25.</li>
<li style="box-sizing: border-box;">obesidad: IMC igual o superior a 30.</li>
</ul>
<p style="box-sizing: border-box; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;"><span style="box-sizing: border-box;">El IMC proporciona la medida m&aacute;s &uacute;til del sobrepeso y la obesidad en la poblaci&oacute;n, pues es la misma para ambos sexos y para los adultos de todas las edades. Sin embargo, hay que considerarla como un valor aproximado porque puede no corresponderse con el mismo nivel de grosor en diferentes personas.</span></p>
<p style="box-sizing: border-box; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;"><span style="box-sizing: border-box;">En el caso de los ni&ntilde;os, es necesario tener en cuenta la edad al definir el sobrepeso y la obesidad.</span></p>
<h3 class="section_head2" style="box-sizing: border-box; font-variant-numeric: normal; font-variant-east-asian: normal; font-weight: normal; font-stretch: normal; font-size: 30px; line-height: 40px; font-family: Arial, Helvetica, sans-serif; color: #3c4245;">Ni&ntilde;os menores de 5 a&ntilde;os</h3>
<p style="box-sizing: border-box; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;"><span style="box-sizing: border-box;">En el caso de los ni&ntilde;os menores de 5 a&ntilde;os:</span></p>
<ul style="box-sizing: border-box; float: inherit; padding-left: 20px; width: 812.219px; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;">
<li style="box-sizing: border-box;">el sobrepeso es el peso para la estatura con m&aacute;s de dos desviaciones t&iacute;picas por encima de la mediana establecida en los patrones de crecimiento infantil de la OMS; y</li>
<li style="box-sizing: border-box;">la obesidad es el peso para la estatura con m&aacute;s de tres desviaciones t&iacute;picas por encima de la mediana establecida en los patrones de crecimiento infantil de la OMS.</li>
</ul>
<ul style="box-sizing: border-box; float: inherit; padding-left: 20px; width: 812.219px; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;">
<li style="box-sizing: border-box;"><a style="text-decoration-line: none; color: #008dc9; box-sizing: border-box;" href="http://www.who.int/entity/childgrowth/standards/weight_for_height/en/index.html">Gr&aacute;ficos y tablas: patrones de crecimiento de la OMS para ni&ntilde;os menores de 5 a&ntilde;os - en ingl&eacute;s</a></li>
</ul>
<h3 class="section_head2" style="box-sizing: border-box; font-variant-numeric: normal; font-variant-east-asian: normal; font-weight: normal; font-stretch: normal; font-size: 30px; line-height: 40px; font-family: Arial, Helvetica, sans-serif; color: #3c4245;">Ni&ntilde;os de 5 a 19 a&ntilde;os</h3>
<p style="box-sizing: border-box; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;"><span style="box-sizing: border-box;">En el caso de los ni&ntilde;os de 5 a 19 a&ntilde;os, el sobrepeso y la obesidad se definen de la siguiente manera:</span></p>
<ul style="box-sizing: border-box; float: inherit; padding-left: 20px; width: 812.219px; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;">
<li style="box-sizing: border-box;">el sobrepeso es el IMC para la edad con m&aacute;s de una desviaci&oacute;n t&iacute;pica por encima de la mediana establecida en los patrones de crecimiento infantil de la OMS, y</li>
<li style="box-sizing: border-box;">la obesidad es mayor que dos desviaciones t&iacute;picas por encima de la mediana establecida en los patrones de crecimiento infantil de la OMS.</li>
</ul>
<ul style="box-sizing: border-box; float: inherit; padding-left: 20px; width: 812.219px; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;">
<li style="box-sizing: border-box;"><a style="text-decoration-line: none; color: #008dc9; box-sizing: border-box;" href="http://www.who.int/entity/growthref/who2007_bmi_for_age/en/index.html">Gr&aacute;ficos y tablas: patrones de crecimiento de la OMS para ni&ntilde;os de 5 a 19 a&ntilde;os - en ingl&eacute;s</a></li>
</ul>
<h2 class="section_head1" style="box-sizing: border-box; font-variant-numeric: normal; font-variant-east-asian: normal; font-weight: normal; font-stretch: normal; font-size: 37px; line-height: 47px; font-family: Arial, Helvetica, sans-serif; color: #3c4245;">Datos sobre el sobrepeso y la obesidad</h2>
<p style="box-sizing: border-box; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;"><span style="box-sizing: border-box;">A continuaci&oacute;n se presentan algunas estimaciones recientes de la OMS a nivel mundial.</span></p>
<ul style="box-sizing: border-box; float: inherit; padding-left: 20px; width: 812.219px; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;">
<li style="box-sizing: border-box;">En 2016, m&aacute;s de 1900 millones de adultos de 18 o m&aacute;s a&ntilde;os ten&iacute;an sobrepeso, de los cuales, m&aacute;s de 650 millones eran obesos.</li>
<li style="box-sizing: border-box;">En 2016, el 39% de los adultos de 18 o m&aacute;s a&ntilde;os (un 39% de los hombres y un 40% de las mujeres) ten&iacute;an sobrepeso.</li>
<li style="box-sizing: border-box;">En general, en 2016 alrededor del 13% de la poblaci&oacute;n adulta mundial (un 11% de los hombres y un 15% de las mujeres) eran obesos.</li>
<li style="box-sizing: border-box;">Entre 1975 y 2016, la prevalencia mundial de la obesidad se ha casi triplicado.</li>
</ul>
<p style="box-sizing: border-box; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;"><span style="box-sizing: border-box;">En 2016, seg&uacute;n las estimaciones unos 41 millones de ni&ntilde;os menores de cinco a&ntilde;os ten&iacute;an sobrepeso o eran obesos. Si bien el sobrepeso y la obesidad se consideraban antes un problema propio de los pa&iacute;ses de ingresos altos, actualmente ambos trastornos aumentan en los pa&iacute;ses de ingresos bajos y medianos, en particular en los entornos urbanos. En &Aacute;frica, el n&uacute;mero de menores de 5 a&ntilde;os con sobrepeso ha aumentado cerca de un 50% desde el a&ntilde;o 2000. En 2016, cerca de la mitad de los ni&ntilde;os menores de cinco a&ntilde;os con sobrepeso u obesidad viv&iacute;an en Asia.</span></p>
<p style="box-sizing: border-box; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;"><span style="box-sizing: border-box;">En 2016 hab&iacute;a m&aacute;s de 340 millones de ni&ntilde;os y adolescentes (de 5 a 19 a&ntilde;os) con sobrepeso u obesidad.</span></p>
<p style="box-sizing: border-box; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;"><span style="box-sizing: border-box;">La prevalencia del sobrepeso y la obesidad en ni&ntilde;os y adolescentes (de 5 a 19 a&ntilde;os) ha aumentado de forma espectacular, del 4% en 1975 a m&aacute;s del 18% en 2016. Este aumento ha sido similar en ambos sexos: un 18% de ni&ntilde;as y un 19% de ni&ntilde;os con sobrepeso en 2016.</span></p>
<p style="box-sizing: border-box; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;"><span style="box-sizing: border-box;">Mientras que en 1975 hab&iacute;a menos de un 1% de ni&ntilde;os y adolescentes de 5 a 19 a&ntilde;os con obesidad, en 2016 eran 124 millones (un 6% de las ni&ntilde;as y un 8% de los ni&ntilde;os).</span></p>
<p style="box-sizing: border-box; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;"><span style="box-sizing: border-box;">A nivel mundial, el sobrepeso y la obesidad est&aacute;n vinculados con un mayor n&uacute;mero de muertes que la insuficiencia ponderal. En general, hay m&aacute;s personas obesas que con peso inferior al normal. Ello ocurre en todas las regiones, excepto en partes de &Aacute;frica subsahariana y Asia.</span></p>
<h2 class="section_head1" style="box-sizing: border-box; font-variant-numeric: normal; font-variant-east-asian: normal; font-weight: normal; font-stretch: normal; font-size: 37px; line-height: 47px; font-family: Arial, Helvetica, sans-serif; color: #3c4245;">&iquest;Qu&eacute; causa el sobrepeso y la obesidad?</h2>
<p style="box-sizing: border-box; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;"><span style="box-sizing: border-box;">La causa fundamental del sobrepeso y la obesidad es un desequilibrio energ&eacute;tico entre calor&iacute;as consumidas y gastadas. A nivel mundial ha ocurrido lo siguiente:</span></p>
<ul style="box-sizing: border-box; float: inherit; padding-left: 20px; width: 812.219px; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;">
<li style="box-sizing: border-box;">un aumento en la ingesta de alimentos de alto contenido cal&oacute;rico que son ricos en grasa; y</li>
<li style="box-sizing: border-box;">un descenso en la actividad f&iacute;sica debido a la naturaleza cada vez m&aacute;s sedentaria de muchas formas de trabajo, los nuevos modos de transporte y la creciente urbanizaci&oacute;n.</li>
</ul>
<p style="box-sizing: border-box; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;"><span style="box-sizing: border-box;">A menudo los cambios en los h&aacute;bitos alimentarios y de actividad f&iacute;sica son consecuencia de cambios ambientales y sociales asociados al desarrollo y de la falta de pol&iacute;ticas de apoyo en sectores como la salud; la agricultura; el transporte; la planificaci&oacute;n urbana; el medio ambiente; el procesamiento, distribuci&oacute;n y comercializaci&oacute;n de alimentos, y la educaci&oacute;n.</span></p>
<h2 class="section_head1" style="box-sizing: border-box; font-variant-numeric: normal; font-variant-east-asian: normal; font-weight: normal; font-stretch: normal; font-size: 37px; line-height: 47px; font-family: Arial, Helvetica, sans-serif; color: #3c4245;">&iquest;Cu&aacute;les son las consecuencias comunes del sobrepeso y la obesidad para la salud?</h2>
<p style="box-sizing: border-box; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;"><span style="box-sizing: border-box;">Un IMC elevado es un importante factor de riesgo de enfermedades no transmisibles, como las siguientes:</span></p>
<ul style="box-sizing: border-box; float: inherit; padding-left: 20px; width: 812.219px; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;">
<li style="box-sizing: border-box;">las enfermedades cardiovasculares (principalmente las cardiopat&iacute;as y los accidentes cerebrovasculares), que fueron la principal causa de muertes en 2012;</li>
<li style="box-sizing: border-box;">la diabetes;</li>
<li style="box-sizing: border-box;">los trastornos del aparato locomotor (en especial la osteoartritis, una enfermedad degenerativa de las articulaciones muy discapacitante), y</li>
<li style="box-sizing: border-box;">algunos c&aacute;nceres (endometrio, mama, ovarios, pr&oacute;stata, h&iacute;gado, ves&iacute;cula biliar, ri&ntilde;ones y colon).</li>
</ul>
<p style="box-sizing: border-box; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;"><span style="box-sizing: border-box;">El riesgo de contraer estas enfermedades no transmisibles crece con el aumento del IMC.</span></p>
<p style="box-sizing: border-box; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;"><span style="box-sizing: border-box;">La obesidad infantil se asocia con una mayor probabilidad de obesidad, muerte prematura y discapacidad en la edad adulta. Sin embargo, adem&aacute;s de estos mayores riesgos futuros, los ni&ntilde;os obesos sufren dificultades respiratorias, mayor riesgo de fracturas e hipertensi&oacute;n, y presentan marcadores tempranos de enfermedades cardiovasculares, resistencia a la insulina y efectos psicol&oacute;gicos.</span></p>
<h2 class="section_head1" style="box-sizing: border-box; font-variant-numeric: normal; font-variant-east-asian: normal; font-weight: normal; font-stretch: normal; font-size: 37px; line-height: 47px; font-family: Arial, Helvetica, sans-serif; color: #3c4245;">Afrontar una doble carga de morbilidad</h2>
<p style="box-sizing: border-box; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;"><span style="box-sizing: border-box;">Actualmente, muchos pa&iacute;ses de ingresos bajos y medianos est&aacute;n afrontando una &laquo;doble carga&raquo; de morbilidad.</span></p>
<ul style="box-sizing: border-box; float: inherit; padding-left: 20px; width: 812.219px; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;">
<li style="box-sizing: border-box;">Mientras estos pa&iacute;ses contin&uacute;an encarando los problemas de las enfermedades infecciosas y la desnutrici&oacute;n, tambi&eacute;n experimentan un r&aacute;pido aumento en los factores de riesgo de las enfermedades no transmisibles, como la obesidad y el sobrepeso, sobre todo en los entornos urbanos.</li>
<li style="box-sizing: border-box;">No es raro encontrar la desnutrici&oacute;n y la obesidad coexistiendo en el mismo pa&iacute;s, la misma comunidad y el mismo hogar.</li>
</ul>
<p style="box-sizing: border-box; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;"><span style="box-sizing: border-box;">En los pa&iacute;ses de ingresos bajos y medianos, es m&aacute;s probable que la nutrici&oacute;n prenatal, del lactante y del ni&ntilde;o peque&ntilde;o sea inadecuada. Al mismo tiempo, los ni&ntilde;os est&aacute;n expuestos a alimentos de alto contenido cal&oacute;rico ricos en grasa, az&uacute;car y sal y pobres en micronutrientes, que suelen costar menos, pero tambi&eacute;n tienen nutrientes de calidad inferior. Estos h&aacute;bitos alimentarios, junto con un nivel inferior de actividad f&iacute;sica, dan lugar a un aumento dr&aacute;stico de la obesidad infantil, al tiempo que los problemas de la desnutrici&oacute;n contin&uacute;an sin resolverse.</span></p>
<h2 class="section_head1" style="box-sizing: border-box; font-variant-numeric: normal; font-variant-east-asian: normal; font-weight: normal; font-stretch: normal; font-size: 37px; line-height: 47px; font-family: Arial, Helvetica, sans-serif; color: #3c4245;">&iquest;C&oacute;mo pueden reducirse el sobrepeso y la obesidad?</h2>
<p style="box-sizing: border-box; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;"><span style="box-sizing: border-box;">El sobrepeso y la obesidad, as&iacute; como las enfermedades no transmisibles vinculadas, pueden prevenirse en su mayor&iacute;a. Son fundamentales unos entornos y comunidades favorables que permitan influir en las elecciones de las personas, de modo que la opci&oacute;n m&aacute;s sencilla (la m&aacute;s accesible, disponible y asequible) sea la m&aacute;s saludable en materia de alimentos y actividad f&iacute;sica peri&oacute;dica, y en consecuencia prevenir el sobrepeso y la obesidad.</span></p>
<p style="box-sizing: border-box; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;"><span style="box-sizing: border-box;">En el plano individual, las personas pueden optar por:</span></p>
<ul style="box-sizing: border-box; float: inherit; padding-left: 20px; width: 812.219px; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;">
<li style="box-sizing: border-box;">limitar la ingesta energ&eacute;tica procedente de la cantidad de grasa total y de az&uacute;cares;</li>
<li style="box-sizing: border-box;">aumentar el consumo de frutas y verduras, as&iacute; como de legumbres, cereales integrales y frutos secos; y</li>
<li style="box-sizing: border-box;">realizar una actividad f&iacute;sica peri&oacute;dica (60 minutos diarios para los j&oacute;venes y 150 minutos semanales para los adultos).</li>
</ul>
<p style="box-sizing: border-box; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;"><span style="box-sizing: border-box;">La responsabilidad individual solo puede tener pleno efecto si las personas tienen acceso a un modo de vida sano. Por consiguiente, en el plano social, es importante ayudar a las personas a seguir las recomendaciones mencionadas, mediante la ejecuci&oacute;n sostenida de pol&iacute;ticas demogr&aacute;ficas y basadas en pruebas cient&iacute;ficas que permitan que la actividad f&iacute;sica peri&oacute;dica y las opciones alimentarias m&aacute;s saludables est&eacute;n disponibles y sean asequibles y f&aacute;cilmente accesibles para todos, en particular para las personas m&aacute;s pobres. Un ejemplo de una pol&iacute;tica de ese tipo es un impuesto sobre las bebidas azucaradas.</span></p>
<p style="box-sizing: border-box; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;"><span style="box-sizing: border-box;">La industria alimentaria puede desempe&ntilde;ar un papel importante en la promoci&oacute;n de dietas sanas del siguiente modo:</span></p>
<ul style="box-sizing: border-box; float: inherit; padding-left: 20px; width: 812.219px; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;">
<li style="box-sizing: border-box;">reduciendo el contenido de grasa, az&uacute;car y sal de los alimentos procesados;</li>
<li style="box-sizing: border-box;">asegurando que las opciones saludables y nutritivas est&eacute;n disponibles y sean asequibles para todos los consumidores;</li>
<li style="box-sizing: border-box;">limitando la comercializaci&oacute;n de alimentos ricos en az&uacute;car, sal y grasas, sobre todo los alimentos destinados a los ni&ntilde;os y los adolescentes; y</li>
<li style="box-sizing: border-box;">garantizando la disponibilidad de opciones alimentarias saludables y apoyando la pr&aacute;ctica de actividades f&iacute;sicas peri&oacute;dicas en el lugar de trabajo.</li>
</ul>
<h2 class="section_head1" style="box-sizing: border-box; font-variant-numeric: normal; font-variant-east-asian: normal; font-weight: normal; font-stretch: normal; font-size: 37px; line-height: 47px; font-family: Arial, Helvetica, sans-serif; color: #3c4245;">Respuesta de la OMS</h2>
<p style="box-sizing: border-box; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;"><span style="box-sizing: border-box;">En la "Estrategia Mundial OMS sobre R&eacute;gimen Alimentario, Actividad F&iacute;sica y Salud", adoptada por la Asamblea Mundial de la Salud en 2004, se describen las medidas necesarias para respaldar las dietas sanas y la actividad f&iacute;sica peri&oacute;dica. En la Estrategia se exhorta a todas las partes interesadas a que adopten medidas a nivel mundial, regional y local para mejorar las dietas y los h&aacute;bitos de actividad f&iacute;sica en la poblaci&oacute;n.</span></p>
<p style="box-sizing: border-box; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;"><span style="box-sizing: border-box;">En la Declaraci&oacute;n pol&iacute;tica de la Reuni&oacute;n de Alto Nivel de la Asamblea General de las Naciones Unidas sobre la Prevenci&oacute;n y el Control de las Enfermedades No Transmisibles, de septiembre de 2011, se reconoce la importancia crucial de reducir la dieta malsana y la inactividad f&iacute;sica. En dicha Declaraci&oacute;n se asume el compromiso de promover la aplicaci&oacute;n de la "Estrategia Mundial OMS sobre R&eacute;gimen Alimentario, Actividad F&iacute;sica y Salud", entre otros medios, seg&uacute;n proceda, introduciendo pol&iacute;ticas y medidas encaminadas a promover dietas sanas y a aumentar la actividad f&iacute;sica de toda la poblaci&oacute;n.</span></p>
<p style="box-sizing: border-box; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;"><span style="box-sizing: border-box;">Asimismo, la OMS ha creado el Plan de acci&oacute;n mundial para la prevenci&oacute;n y el control de las enfermedades no transmisibles 2013-2020, que tiene por objeto cumplir los compromisos de la Declaraci&oacute;n Pol&iacute;tica de las Naciones Unidas sobre las Enfermedades No Transmisibles, que recibi&oacute; el respaldo de los Jefes de Estado y de Gobierno en septiembre de 2011. El Plan de acci&oacute;n mundial contribuir&aacute; a realizar avances en nueve metas mundiales relativas a las enfermedades no transmisibles que deben alcanzarse no m&aacute;s tarde de 2025, incluidas una reducci&oacute;n relativa del 25% en la mortalidad prematura a causa de dichas enfermedades para 2025 y una detenci&oacute;n del aumento de la obesidad mundial para coincidir con las tasas de 2010.</span></p>
<p style="box-sizing: border-box; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;"><span style="box-sizing: border-box;">La Asamblea Mundial de la Salud acogi&oacute; con satisfacci&oacute;n el informe de la Comisi&oacute;n para acabar con la obesidad infantil (2016) y sus seis recomendaciones a fin de dar respuesta al entorno obesog&eacute;nico y los periodos cruciales en el ciclo de vida de manera que se combatiera la obesidad infantil. La Asamblea Mundial de la Salud de 2017 acogi&oacute; favorablemente el plan de aplicaci&oacute;n destinado a orientar a los pa&iacute;ses en la puesta en pr&aacute;ctica de las recomendaciones de la Comisi&oacute;n.</span></p>
<p style="box-sizing: border-box; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;">&nbsp;</p>
<div style="box-sizing: border-box; color: #3c4245; font-family: Arial, Helvetica, sans-serif; font-size: 16px;">&nbsp;</div>',
  'image' => 'posts/August2018/dJCLyrGrAEP4yvWNY75w.jpg',
  'slug' => 'obesidad-y-sobrepeso',
  'meta-description' => 'This is the meta description',
  'meta-keywords' => 'keyword1, keyword2, keyword3',
  'status' => 'PUBLISHED',
  'featured' => 0,
          ],
          [
            'author_id' => '1',
            'title' => 'TOP 8 PARA PECTORALES',
            'excerpt' => 'Es muy importante comprender los músculos del pecho antes de nada, ya que conocer en profundidad de qué músculos se compone el pectoral es fundamental para poder trabajarlo bien.',
            'body' => '<p><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #333333;">Una consulta super recurrente que nos hacen los atletas que nos siguen, es c&oacute;mo realizar un entreno espec&iacute;fico de pectorales que nos permita focalizar el trabajo en ellos. Vemos que uno de los problemas m&aacute;s habituales es que con las rutinas m&aacute;s extendidas, no sentimos que el pecho trabaje lo suficiente, si no que incluso sentimos que m&uacute;sculos como los tr&iacute;ceps hacen esfuerzo y trabajo mayor que los propios pectorales.</span></p>
<p><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #333333;">Es muy importante comprender los m&uacute;sculos del pecho antes de nada, ya que conocer en profundidad de qu&eacute; m&uacute;sculos se compone el pectoral es fundamental para poder trabajarlo bien. &nbsp;El pecho se compone de dos m&uacute;sculos; el pectoral mayor y el pectoral menor.</span></p>
<p><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #333333;">Con el objetivo de trabajar el pectoral, tenemos que hacer que se contraiga a lo largo de sus fibras musculares, para ello tenemos dos tipos de ejercicios que ayudan a desarrollarlos plenamente, unos para el pectoral superior y otros para el inferior.</span></p>
<p><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #333333;">Hay una creencia extendida pero falsa de que que la parte superior del pecho es un m&uacute;sculo diferente, pero el pectoral menor es un m&uacute;sculo delgado ubicado debajo del pectoral mayor y su funci&oacute;n principal es llevar el hombro y el brazo hacia abajo.</span></p>
<p><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #333333;">Hoy vamos a ver los ejercicios m&aacute;s recomendados para trabajar de forma integral y completa el pectoral.</span></p>
<p>&nbsp;</p>
<p><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #333333;"><img title="Pectorales" src="http://maxeffortchallenge.com/storage/posts/August2018/ganar-masa-muscular-forzaa.jpg" alt="Muscle" width="1000" height="522" /></span></p>
<p>&nbsp;</p>
<h2 style="box-sizing: border-box; font-family: AntonioRegular, sans-serif; font-weight: 500; line-height: 44px; color: #333333; margin: 20px 0px 10px; font-size: 36px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; vertical-align: baseline; text-rendering: optimizeLegibility;"><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: 21px; font-family: inherit; vertical-align: baseline;">Top Pectorales Inferiores</strong></span></h2>
<p><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: #333333;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: 21px; font-family: inherit; vertical-align: baseline;">Dips o fondos en paralelas</strong></span></p>
<p><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #333333;">Con diferencia, es el mejor ejercicio para trabajar las fibras m&aacute;s bajas de los pectorales. Su ejecuci&oacute;n es sencilla y trabaja con nuestro propio peso. Es un buen ejercicio para comenzar a trabajar los pectorales</span></p>
<p><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: #333333;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: 21px; font-family: inherit; vertical-align: baseline;">Banco de press con mancuerna &nbsp;</strong></span></p>
<p><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #333333;">Este ejercicio cl&aacute;sico es muy &uacute;til para trabajar los pectorales, el peso debemos ir a&ntilde;adi&eacute;ndolo de forma progresiva y como siempre decimos, debemos incluir el que nos permita seguir realizando bien la t&eacute;cnica. En cuanto el peso nos obligue a cambiar la postura correcta, debemos bajarlo. De cara a evitar desgarro es importante practicarlo con suma prudencia cuando las cargas son importantes.</span></p>
<p><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: #333333;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: 21px; font-family: inherit; vertical-align: baseline;">Press de Banca con barra</strong></span></p>
<p><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #333333;">Al realizar este ejercicio es fundamental prestar atenci&oacute;n a tus codos, no deben ensancharse, tienen que subir y bajar en un &aacute;ngulo de 45 grados hacia los pies. Este ejercicio es muy completo ya que trabaja el pectoral superior, el pectoral inferior, los tr&iacute;ceps y los deltoides anteriores.</span></p>
<p><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #333333;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: 21px; font-family: inherit; vertical-align: baseline;">Cable cruzado</strong></span></p>
<p><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #333333;">El ejercicio de cables cruzados se puede realizar sentado, pero nuestra recomendaci&oacute;n es realizarlo de pie ya que es m&aacute;s efectivo. Cuando hagas este ejercicio, te recomendamos tambi&eacute;n mantener una posici&oacute;n con las piernas completamente separadas para tener una base de soporte estable.</span></p>
<p><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: #333333;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: 21px; font-family: inherit; vertical-align: baseline;">Dumbbell Fly</strong></span></p>
<p>&nbsp;</p>
<p><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #333333;">Este ejercicio es recomendado para atletas que ya tengan fuerza suficiente en los pectorales y sobretodo que tengan trayectoria de entreno. Realizando correctamente este ejercicio trabajamos deltoides, pectorales y m&uacute;sculos secundarios de los brazos y la espalda.&nbsp; </span></p>
<p>&nbsp;</p>
<h2 style="box-sizing: border-box; font-family: AntonioRegular, sans-serif; font-weight: 500; line-height: 44px; color: #333333; margin: 20px 0px 10px; font-size: 36px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; vertical-align: baseline; text-rendering: optimizeLegibility;"><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: 21px; font-family: inherit; vertical-align: baseline;">Top Pectorales Superiores</strong></span></h2>
<p><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #333333;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: 21px; font-family: inherit; vertical-align: baseline;">Press de Banca inclinado.</strong></span></p>
<p><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #333333;">Lo realizamos igual que un press de banca normal, pero a&ntilde;adimos una pendiente. No bajamos la barra hacia el pecho, bajamos hasta que los brazos superiores est&eacute;n paralelos al suelo. Como m&iacute;nimo, tenemos que realizar 5-6 repeticiones.</span></p>
<p><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: #333333;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: 21px; font-family: inherit; vertical-align: baseline;">Dumbbell Bench Press</strong></span></p>
<p><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: #333333;"><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">El press de banca con mancuernas</span>&nbsp;<span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline;">es una variante que cambia sustancialmente los m&uacute;sculos involucrados en el movimiento frente al press de barra. Es importante tener ya cierta fuerza adquirida para realizarlo. Con el trabajaremos pectoral mayor clavicular, deltoides, tr&iacute;ceps braquial, b&iacute;ceps braquial, etc.</span></span></p>
<p><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #333333;"><strong style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: 21px; font-family: inherit; vertical-align: baseline;">Dumbbell Fly inclinado:</strong></span></p>
<p><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #333333;">Este ejercicio tambi&eacute;n requiere trayectoria de entreno. Para trabajar efectivamente los m&uacute;sculos de tus pectorales, vigila que los movimientos hacia arriba y abajo se inicien y contin&uacute;en con una contracci&oacute;n de los m&uacute;sculos del pecho y no los deltoides.</span></p>
<p><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #333333;">Para evitar posibles lesiones, mant&eacute;n la cabeza y la espalda en contacto con la banca en todo el ejercicio y conc&eacute;ntrate en hiperextender las mu&ntilde;ecas para que se toquen ellas, en lugar de las mancuernas.</span></p>
<p style="box-sizing: border-box; margin: 0px 0px 22px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-stretch: inherit; line-height: inherit; font-family: RobotoRegular; vertical-align: baseline; color: #9e9e9e;">&nbsp;</p>
<p><span style="box-sizing: border-box; margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-stretch: inherit; font-size: inherit; line-height: inherit; font-family: inherit; vertical-align: baseline; color: #333333;"><span style="font-family: inherit; font-size: inherit; font-style: inherit; font-variant-ligatures: inherit; font-variant-caps: inherit; font-weight: inherit;">En definitiva esperamos que construyas tus pectorales de acero con estos 8 ejercicios.</span>&nbsp;</span></p>',
  'image' => 'posts/August2018/P7XTYJsb02ZeEGISamFg.jpg',
  'slug' => 'top-8-para-pectorales',
  'meta-description' => 'Meta Description for sample post',
  'meta-keywords' => 'keyword1, keyword2, keyword3',
  'status' => 'PUBLISHED',
  'featured' => 0,
          ],

          [
            'author_id' => '1',
            'title' => 'Cinco razones por las que te sientes bien después de practicar crossfit',
            'excerpt' => 'Crossfit es una actividad deportiva igual que cualquier otra, pero caracterizada por la alta intensidad con la que se ejecutan sus ejercicios y por los buenos resultados que nos produce tanto a nivel físico como a nivel emocional.',
            'body' => '<p style="box-sizing: border-box; font-family: Verdana, Geneva, sans-serif; font-size: 15px; line-height: 26px; margin-top: 0px; margin-bottom: 26px; word-wrap: break-word; color: #222222;"><span style="box-sizing: border-box;">Como ya sabes, practicar cualquier deporte de cierta intensidad repercute positivamente en tu estado de &aacute;nimo debido a una serie de cambios fisiol&oacute;gicos que se producen en tu cuerpo, provocando una retroalimentaci&oacute;n positiva a nivel emocional, imprescindible para poder practicar dicho deporte de forma continuada.</span></p>
<p style="box-sizing: border-box; font-family: Verdana, Geneva, sans-serif; font-size: 15px; line-height: 26px; margin-top: 0px; margin-bottom: 26px; word-wrap: break-word; color: #222222;"><span style="box-sizing: border-box;">Pero m&aacute;s concretamente, la pr&aacute;ctica de crossfit te dejar&aacute; huella por cinco razones principales:</span></p>
<div class="td-paragraph-padding-4" style="box-sizing: border-box; padding-left: 27.8281px; padding-right: 0px; color: #222222; font-family: Verdana, Geneva, sans-serif; font-size: 15px;">
<h3 style="box-sizing: border-box; font-family: roboto, sans-serif; color: #111111; font-weight: 400; margin: 27px 0px 17px; font-size: 22px; line-height: 30px;"><span style="box-sizing: border-box; font-weight: bold;">1&ordf; Raz&oacute;n: vas a descubrir lo feliz que te hacen las hormonas</span></h3>
<p style="box-sizing: border-box; line-height: 26px; margin-top: 0px; margin-bottom: 26px; word-wrap: break-word;"><span style="box-sizing: border-box;">No es que tus hormonas sean intercambiables ni tampoco que existan hormonas para personas sedentarias y hormonas para personas activas, sino que al realizar un deporte de alta intensidad como es crossfit, nuestro cuerpo produce una descarga de hormonas enorme, responsables &eacute;stas de esa sensaci&oacute;n de calma y de satisfacci&oacute;n que sentimos al acabar la sesi&oacute;n.</span></p>
<p style="box-sizing: border-box; line-height: 26px; margin-top: 0px; margin-bottom: 26px; word-wrap: break-word;"><span style="box-sizing: border-box;">De entre ellas, siempre se ha destacado a las archifamosas endorfinas, a la serotonina o a la dopamina, todas ellas muy vinculadas desde el punto de vista cient&iacute;fico a las adaptaciones neurofisiol&oacute;gicas de las adicciones.</span></p>
<p style="box-sizing: border-box; line-height: 26px; margin-top: 0px; margin-bottom: 26px; word-wrap: break-word;"><span style="box-sizing: border-box;">A&uacute;n as&iacute;, en el siguiente art&iacute;culo se explicar&aacute; con mayor lujo de detalles el papel espec&iacute;fico de varias de estas hormonas ya conocidas y de otras menos famosas, pero igual de influyentes y que muestran c&oacute;mo los endocannabinoides, por ejemplo, son pieza fundamental en la producci&oacute;n de esa sensaci&oacute;n de bienestar postejercicio.</span></p>
<h3 style="box-sizing: border-box; font-family: roboto, sans-serif; color: #111111; font-weight: 400; margin: 27px 0px 17px; font-size: 22px; line-height: 30px;"><span style="box-sizing: border-box; font-weight: bold;">2&ordf; Raz&oacute;n: te sentir&aacute;s igual de bien hayas hecho el WOD en el mejor tiempo o no . La alta intensidad de los ejercicios genera tambi&eacute;n una gran satisfacci&oacute;n a nivel deportivo</span></h3>
<p style="box-sizing: border-box; line-height: 26px; margin-top: 0px; margin-bottom: 26px; word-wrap: break-word;"><span style="box-sizing: border-box;">La otra cara del deporte y a menudo la olvidada es la de la satisfacci&oacute;n personal de vencerse a uno mismo, la de entregarnos al cien por cien en nuestro entrenamiento siendo conscientes de nuestros l&iacute;mites y siempre en funci&oacute;n del tipo de vida que llevamos. Y para muestra, imag&iacute;nate en un WOD cualquiera de tu box en el que para unos trepar la cuerda en menos de nueve segundos ser&aacute; un logro enorme para su time cap final, mientras que para otros terminar el WOD habiendo trepado y descendido la cuerda ser&aacute; un subid&oacute;n igual o mayor. De ah&iacute; que la pr&aacute;ctica de crossfit no perjudique a la satisfacci&oacute;n deportiva que producen las metas conseguidas.</span></p>
<h3 style="box-sizing: border-box; font-family: roboto, sans-serif; color: #111111; font-weight: 400; margin: 27px 0px 17px; font-size: 22px; line-height: 30px;"><span style="box-sizing: border-box; font-weight: bold;">3&ordf; Raz&oacute;n: la mejora en tu rendimiento deportivo es exponencial</span></h3>
<p style="box-sizing: border-box; line-height: 26px; margin-top: 0px; margin-bottom: 26px; word-wrap: break-word;"><span style="box-sizing: border-box;">El ejercicio de alta intensidad es tremendamente pr&aacute;ctico y est&aacute; totalmente en l&iacute;nea con lo que le pedimos a cualquier deporte hoy en d&iacute;a: m&aacute;xima eficiencia en el menor tiempo posible.</span></p>
<p style="box-sizing: border-box; line-height: 26px; margin-top: 0px; margin-bottom: 26px; word-wrap: break-word;"><span style="box-sizing: border-box;">Te vas a sentir bien practicando crossfit porque vas a ver c&oacute;mo tu cuerpo va a coger forma mucho m&aacute;s r&aacute;pido que con cualquier otro ejercicio de cardio muy prolongado en el tiempo y sin necesidad de realizar entrenamientos diarios de varias horas &nbsp;de duraci&oacute;n.</span></p>
<p style="box-sizing: border-box; line-height: 26px; margin-top: 0px; margin-bottom: 26px; word-wrap: break-word;"><span style="box-sizing: border-box;">Entrenamientos de menos de una hora entre dos y tres veces por semana van a darle un feedback realmente positivo tanto a tu cuerpo como a tu mente.</span></p>
<h3 style="box-sizing: border-box; font-family: roboto, sans-serif; color: #111111; font-weight: 400; margin: 27px 0px 17px; font-size: 22px; line-height: 30px;"><span style="box-sizing: border-box; font-weight: bold;">4&ordf; Raz&oacute;n:&nbsp;</span><span style="box-sizing: border-box; font-weight: bold;">el trabajo en grupo genera sensaci&oacute;n de bienestar</span></h3>
<p style="box-sizing: border-box; line-height: 26px; margin-top: 0px; margin-bottom: 26px; word-wrap: break-word;"><span style="box-sizing: border-box;">Como ya escrib&iacute; en un&nbsp;</span><a style="box-sizing: border-box; background-color: transparent; color: #eb9812; text-decoration-line: none;" href="https://infowod.com/cinco-razones-las-practicar-crossfit/">art&iacute;culo</a><span style="box-sizing: border-box;">&nbsp;anterior, las ventajas del entrenamiento en grupo que se lleva a cabo en crossfit son m&uacute;ltiples, tanto a nivel f&iacute;sico como emocional.</span></p>
<p style="box-sizing: border-box; line-height: 26px; margin-top: 0px; margin-bottom: 26px; word-wrap: break-word;"><span style="box-sizing: border-box;">Dicha conclusi&oacute;n viene apoyada a su vez por un estudio de la Universidad de Oxford sobre la mejora en el rendimiento deportivo, en el que se analiz&oacute; a un grupo de regatistas de la misma universidad remando: unos fueron analizados de forma individual y &nbsp;otros en grupo.</span></p>
<p style="box-sizing: border-box; line-height: 26px; margin-top: 0px; margin-bottom: 26px; word-wrap: break-word;"><span style="box-sizing: border-box;">Los datos finales respaldan la teor&iacute;a que apoya el entrenamiento en grupo como algo positivo en el rendimiento deportivo futuro, ya que cuando los deportistas remaban juntos, la segregaci&oacute;n de hormonas era mucho m&aacute;s elevada que cuando remaban solos, aumentando su capacidad competitiva y su nivel de resistencia. Lo llamaron en el estudio como la&nbsp;</span><em style="box-sizing: border-box;">&ldquo;euforia del remero&rdquo;</em><span style="box-sizing: border-box;">. Es decir, la sensaci&oacute;n de bienestar del entrenamiento en grupo tiene su base cient&iacute;fica y est&aacute; comprobada.</span></p>
<h3 style="box-sizing: border-box; font-family: roboto, sans-serif; color: #111111; font-weight: 400; margin: 27px 0px 17px; font-size: 22px; line-height: 30px;"><span style="box-sizing: border-box; font-weight: bold;">5&ordf; Raz&oacute;n: te ayudar&aacute; a tener la mente m&aacute;s limpia</span></h3>
<p style="box-sizing: border-box; line-height: 26px; margin-top: 0px; margin-bottom: 26px; word-wrap: break-word;"><span style="box-sizing: border-box;">Si los efectos a corto plazo del entrenamiento de crossfit son tremendamente positivos, los efectos a largo plazo no lo son menos.</span></p>
<p style="box-sizing: border-box; line-height: 26px; margin-top: 0px; margin-bottom: 26px; word-wrap: break-word;"><span style="box-sizing: border-box;">En esta l&iacute;nea, y sali&eacute;ndonos un poco del aspecto f&iacute;sico, a nivel mental ver&aacute;s como la pr&aacute;ctica de crossfit te hace tener la mente &ldquo;m&aacute;s limpia&rdquo;, ayud&aacute;ndote a pensar con mayor claridad y a tener m&aacute;s claras tus metas.</span></p>
<p style="box-sizing: border-box; line-height: 26px; margin-top: 0px; margin-bottom: 26px; word-wrap: break-word;"><span style="box-sizing: border-box;">Hace unos a&ntilde;os se llev&oacute; a cabo un estudio con un equipo ciclista semiprofesional en el que se quiso analizar el efecto que el ejercicio intenso produc&iacute;a a nivel cerebral. Tras varios an&aacute;lisis, se lleg&oacute; a la conclusi&oacute;n de que el ejercicio intenso al que se someti&oacute; al grupo ciclista produjo un aumento considerable del n&uacute;mero de prote&iacute;nas en el cerebro encargadas de generar neuronas nuevas y de llevar a cabo la conexi&oacute;n entre ellas, es decir, la conexi&oacute;n interneuronal est&aacute; muy vinculada al ejercicio f&iacute;sico y a la intensidad que pongamos en el mismo. Algo que en nuestros boxes es bien sabido.</span></p>
<p style="box-sizing: border-box; line-height: 26px; margin-top: 0px; margin-bottom: 26px; word-wrap: break-word;"><span style="box-sizing: border-box;">Resumiendo, practicar cualquier deporte con cabeza es un h&aacute;bito excelente para nuestro cuerpo y para nuestra mente. Es el ingrediente ideal para lograr el equilibrio que en tantas facetas de nuestra vida necesitamos.</span></p>
<p style="box-sizing: border-box; line-height: 26px; margin-top: 0px; margin-bottom: 26px; word-wrap: break-word;"><span style="box-sizing: border-box;">Practicar crossfit te va a dar ese plus que la alta intensidad nos ofrece y que repercute tanto en el aumento de la segregaci&oacute;n de hormonas en nuestro cuerpo como en la intensidad de las sensaciones que vamos a tener al acabar nuestras sesiones.</span></p>
</div>',
  'image' => 'posts/August2018/bHrrmITGdPYjUhpOufqb.jpg',
  'slug' => 'cinco-razones-por-las-que-te-sientes-bien-despues-de-practicar-crossfit',
  'meta-description' => 'Meta Description for sample post',
  'meta-keywords' => 'keyword1, keyword2, keyword3',
  'status' => 'PUBLISHED',
  'featured' => 0,
          ],
          [
            'author_id' => '1',
            'title' => 'Los bloqueos: ¿por qué no avanzamos?',
            'excerpt' => '¡Uf!, no puedo lanzarme a la pared, me da muchísimo miedo”
“No estoy relajado, cuando quiero hacer dobles me acelero y no enlazo más de 3”
“Me di un señor hostión haciendo un jerk y me rompí la nariz. No he vuelto a hacer uno bien”',
            'body' => '<div class="td-paragraph-padding-4" style="box-sizing: border-box; padding-left: 27px; padding-right: 0px;">En el d&iacute;a a d&iacute;a de un box se suele escuchar este tipo de comentarios y pueden venir de cualquier tipo de compa&ntilde;ero: de los que van por hobbie, de los que compiten, hasta de los coaches. Se trata de un destino que todos firmamos cuando decidimos apuntarnos a crossfit, porque, al ser un deporte tan variado, siempre va a haber algo que no logramos realizar (al menos no a la primera).</div>
<div class="td-paragraph-padding-4" style="box-sizing: border-box; padding-left: 27.8281px; padding-right: 0px; color: #222222; font-family: Verdana, Geneva, sans-serif; font-size: 15px;">
<p style="box-sizing: border-box; line-height: 26px; margin-top: 0px; margin-bottom: 26px; word-wrap: break-word;"><span style="box-sizing: border-box;">Seas el tipo de usuario que seas, si entre tus objetivos est&aacute; superarte a ti mismo, es necesario empezar por plantearse lo siguiente:</span></p>
<ol style="box-sizing: border-box; padding: 0px; margin-bottom: 26px;">
<li style="box-sizing: border-box; line-height: 26px; margin-left: 21px;"><span style="box-sizing: border-box;">Responder a la pregunta&nbsp;</span><span style="box-sizing: border-box; font-weight: bold;">&ldquo;&iquest;a d&oacute;nde quiero llegar?&rdquo;</span><span style="box-sizing: border-box;">&nbsp;(hacer muscle-up en anillas, llegar a 100 kg de back squat, correr &nbsp;400 m por debajo de 1&rsquo;30&rsquo;&rsquo;&hellip;).</span></li>
<li style="box-sizing: border-box; line-height: 26px; margin-left: 21px;"><span style="box-sizing: border-box;">Descubrir&nbsp;</span><span style="box-sizing: border-box; font-weight: bold;">qu&eacute; me lo est&aacute; impidiendo</span><span style="box-sizing: border-box;">.</span></li>
<li style="box-sizing: border-box; line-height: 26px; margin-left: 21px;"><span style="box-sizing: border-box; font-weight: bold;">Poner una soluci&oacute;n</span><span style="box-sizing: border-box;">&nbsp;acorde a mi caso.</span></li>
</ol>
<p style="box-sizing: border-box; line-height: 26px; margin-top: 0px; margin-bottom: 26px; word-wrap: break-word;"><span style="box-sizing: border-box;">Partiendo de la base de que tienes claro cu&aacute;l es tu objetivo, vamos a poner el foco en el segundo paso. Aqu&iacute; la pregunta del mill&oacute;n es:&nbsp;</span><span style="box-sizing: border-box; font-weight: bold;">&iquest;por qu&eacute; no consigo ejecutar el ejercicio?</span><span style="box-sizing: border-box;">, o&nbsp;</span><span style="box-sizing: border-box; font-weight: bold;">&iquest;por qu&eacute; antes s&iacute; y ahora no?</span><span style="box-sizing: border-box;">&nbsp;Cada uno tendr&aacute; sus razones, pero para acotar el mar de experiencias personales, os voy a hablar de las dos posibilidades que se pueden presentar:</span></p>
<ul style="box-sizing: border-box; padding: 0px; margin-bottom: 26px;">
<li style="box-sizing: border-box; line-height: 26px; margin-left: 21px;"><span style="box-sizing: border-box; font-weight: bold;">Barreras f&iacute;sicas</span><span style="box-sizing: border-box;"><span style="box-sizing: border-box; font-weight: bold;">:</span>&nbsp;aqu&iacute; el problema es que, o bien no dispones de una t&eacute;cnica lo suficientemente pulida para realizar el/los movimiento(s), o bien no tienes la suficiente fuerza/movilidad/flexibilidad, pudi&eacute;ndose dar ambos casos a la vez.</span></li>
<li style="box-sizing: border-box; line-height: 26px; margin-left: 21px;"><span style="box-sizing: border-box; font-weight: bold;">Barreras mentales</span><span style="box-sizing: border-box;"><span style="box-sizing: border-box; font-weight: bold;">:</span>&nbsp;no se ven y muchas veces tampoco se sabe explicar por qu&eacute; aparecen exactamente, pero en ese preciso momento te quedas en blanco y pierdes el control de tu cuerpo, siendo totalmente incapaz de realizar lo que te piden. Son com&uacute;nmente llamadas &ldquo;</span><span style="box-sizing: border-box; font-weight: bold;">bloqueos</span><span style="box-sizing: border-box;">&rdquo; y pueden suponer realmente un quebradero de cabeza.</span></li>
</ul>
<p style="box-sizing: border-box; line-height: 26px; margin-top: 0px; margin-bottom: 26px; word-wrap: break-word;"><span style="box-sizing: border-box;">&nbsp;</span>&nbsp;<span style="box-sizing: border-box;">Si tras analizar tu caso llegas a la conclusi&oacute;n de que tu barrera es &uacute;nicamente f&iacute;sica, muy probablemente con trabajar la t&eacute;cnica y/o tu condici&oacute;n f&iacute;sica sea m&aacute;s que suficiente para solucionar el estancamiento. Pero si estamos ante un bloqueo mental, da igual que tengas una condici&oacute;n f&iacute;sica excelente y que tu t&eacute;cnica sea digna de olimpiadas, porque el trabajo principal no va a estar dirigido a mejorar tu cuerpo o tus habilidades, sino a liberar tu cabeza.</span></p>
<h2 style="box-sizing: border-box; font-family: roboto, sans-serif; color: #111111; font-weight: 400; margin: 30px 0px 20px; font-size: 27px; line-height: 38px;"><span style="box-sizing: border-box; font-weight: bold;">&iquest;Qu&eacute; son los bloqueos mentales? Causas y consecuencias</span></h2>
<p style="box-sizing: border-box; line-height: 26px; margin-top: 0px; margin-bottom: 26px; word-wrap: break-word;"><span style="box-sizing: border-box;">&nbsp;</span>&nbsp;<span style="box-sizing: border-box;">El&nbsp;</span><span style="box-sizing: border-box; font-weight: bold;">bloqueo mental</span><span style="box-sizing: border-box;">&nbsp;es una resistencia provocada por una emoci&oacute;n o pensamiento que queremos evitar. &nbsp;Sirve como mecanismo de defensa ante esas situaciones que pueden perturbarnos y se pone en marcha de manera autom&aacute;tica.</span></p>
<p style="box-sizing: border-box; line-height: 26px; margin-top: 0px; margin-bottom: 26px; word-wrap: break-word;"><span style="box-sizing: border-box;">La sensaci&oacute;n de estar bloqueado se caracteriza por una falta total de control de nosotros mismos: merman nuestras funciones mentales (pensar, atender, procesar informaci&oacute;n&hellip;) y nuestros movimientos se vuelven torpes, hasta llegar al punto de no avanzar. En resumen, dejamos de ser due&ntilde;os de nuestras acciones y decisiones, pudiendo caer en un c&iacute;rculo vicioso que no nos permitir&aacute; evolucionar.</span></p>
<h3 style="box-sizing: border-box; font-family: roboto, sans-serif; color: #111111; font-weight: 400; margin: 27px 0px 17px; font-size: 22px; line-height: 30px;"><span style="box-sizing: border-box; font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&iquest;Por qu&eacute; nos bloqueamos?</span></h3>
<p style="box-sizing: border-box; line-height: 26px; margin-top: 0px; margin-bottom: 26px; word-wrap: break-word;"><span style="box-sizing: border-box;">Por un lado, puede ser por un periodo puntual en el que estamos muy estresados o cansados (exceso de trabajo, situaciones cotidianas, falta de descanso, sobreentrenamiento&hellip;), en cuyo caso lo mejor es no forzar la m&aacute;quina y permitirnos volver a la normalidad antes de enfrentarnos a nuevos retos. O, por otro lado, puede ser por motivos relacionados con el deporte:</span></p>
<ul style="box-sizing: border-box; padding: 0px; margin-bottom: 26px;">
<li style="box-sizing: border-box; line-height: 26px; margin-left: 21px;">
<h4 style="box-sizing: border-box; font-family: roboto, sans-serif; color: #111111; font-weight: 400; margin: 24px 0px 14px; font-size: 19px; line-height: 29px;"><span style="box-sizing: border-box; font-weight: bold;">Miedo</span></h4>
</li>
</ul>
<p style="box-sizing: border-box; line-height: 26px; margin-top: 0px; margin-bottom: 26px; word-wrap: break-word;"><span style="box-sizing: border-box;">Sensaci&oacute;n de angustia ante un peligro real o imaginario. En nuestro caso, podemos sentir miedo&nbsp;</span><span style="box-sizing: border-box; font-weight: bold;">a hacernos da&ntilde;o</span><span style="box-sizing: border-box;">&nbsp;(caerme en el salto a caj&oacute;n, que me d&eacute; un tir&oacute;n en el lumbar si subo el peso en barra&hellip;) o&nbsp;</span><span style="box-sizing: border-box; font-weight: bold;">a sentirnos juzgados</span><span style="box-sizing: border-box;">&nbsp;(&ldquo;&iquest;hacer butterfly? Van a pensar que soy un pato mareado&rdquo;, &ldquo;a ver si me tocan jueces buenos en la competi o estoy fuera&rdquo;&hellip;).</span></p>
<ul style="box-sizing: border-box; padding: 0px; margin-bottom: 26px;">
<li style="box-sizing: border-box; line-height: 26px; margin-left: 21px;">
<h4 style="box-sizing: border-box; font-family: roboto, sans-serif; color: #111111; font-weight: 400; margin: 24px 0px 14px; font-size: 19px; line-height: 29px;"><span style="box-sizing: border-box; font-weight: bold;">Necesidad de aprobaci&oacute;n<span style="box-sizing: border-box; font-weight: 400;">:</span></span></h4>
</li>
</ul>
<p style="box-sizing: border-box; line-height: 26px; margin-top: 0px; margin-bottom: 26px; word-wrap: break-word;"><span style="box-sizing: border-box; font-weight: bold;"><span style="box-sizing: border-box; font-weight: 400;">De aqu&iacute; proviene el miedo a ser juzgados. Lo que ocurre es que nos obsesionamos con lo que opinan los dem&aacute;s (nuestro coach, compa&ntilde;eros, familiares&hellip;) hasta el punto de no ser objetivos con nuestro trabajo y el nivel en el que nos encontramos. Suele darse mayormente en competidores, porque dependen del juicio de otros para validar su trabajo como atletas y saben que con dar lo mejor de s&iacute; mismos puede no ser suficiente.</span></span></p>
<ul style="box-sizing: border-box; padding: 0px; margin-bottom: 26px;">
<li style="box-sizing: border-box; line-height: 26px; margin-left: 21px;">
<h4 style="box-sizing: border-box; font-family: roboto, sans-serif; color: #111111; font-weight: 400; margin: 24px 0px 14px; font-size: 19px; line-height: 29px;"><span style="box-sizing: border-box; font-weight: bold;">Baja confianza:</span></h4>
</li>
</ul>
<p style="box-sizing: border-box; line-height: 26px; margin-top: 0px; margin-bottom: 26px; word-wrap: break-word;"><span style="box-sizing: border-box;">Cuando realmente no tenemos la seguridad de que algo nos va a salir bien o de que vamos a ser capaces de afrontar el reto (&ldquo;no tengo fuerza para hacer fondos sin apoyar rodillas&rdquo;). Nos juzgamos duramente y no valoramos los &eacute;xitos obtenidos.</span></p>
<ul style="box-sizing: border-box; padding: 0px; margin-bottom: 26px;">
<li style="box-sizing: border-box; line-height: 26px; margin-left: 21px;">
<h4 style="box-sizing: border-box; font-family: roboto, sans-serif; color: #111111; font-weight: 400; margin: 24px 0px 14px; font-size: 19px; line-height: 29px;"><span style="box-sizing: border-box; font-weight: bold;">Alta exigencia y perfeccionismo:</span></h4>
</li>
</ul>
<p style="box-sizing: border-box; line-height: 26px; margin-top: 0px; margin-bottom: 26px; word-wrap: break-word;"><span style="box-sizing: border-box;">Ocurre cuando tenemos objetivos muy ambiciosos o cuando nos exigimos por encima de nuestras posibilidades. Nos recriminamos el m&iacute;nimo fallo y no estamos conformes con lo que llevamos acumulado hasta ahora. El ejemplo m&aacute;s t&iacute;pico podemos verlo en ese compa&ntilde;ero nuevo que no ha hecho halterofilia en su vida pero ya quiere hacer el WOD con el peso RX, desde luego muestra valent&iacute;a pero nada de sentido com&uacute;n.</span></p>
<ul style="box-sizing: border-box; padding: 0px; margin-bottom: 26px;">
<li style="box-sizing: border-box; line-height: 26px; margin-left: 21px;">
<h4 style="box-sizing: border-box; font-family: roboto, sans-serif; color: #111111; font-weight: 400; margin: 24px 0px 14px; font-size: 19px; line-height: 29px;"><span style="box-sizing: border-box; font-weight: bold;">Presiones externas:</span></h4>
</li>
</ul>
<p style="box-sizing: border-box; line-height: 26px; margin-top: 0px; margin-bottom: 26px; word-wrap: break-word;"><span style="box-sizing: border-box;">A veces no somos nosotros, sino los dem&aacute;s, los que quieren verte dar m&aacute;s de lo que ten&iacute;as planeado. Por ejemplo, ese coach que, con toda su buena intenci&oacute;n, te ordena quitarte la goma para las dominadas o cuando te exigen mover &ldquo;x&rdquo; peso en cargada, porque &ldquo;para tu nivel, es lo que deber&iacute;as estar haciendo&rdquo;. Estamos satisfechos con lo que damos, pero nos incomoda pensar que los dem&aacute;s no est&aacute;n contentos con nuestros resultados.</span></p>
<ul style="box-sizing: border-box; padding: 0px; margin-bottom: 26px;">
<li style="box-sizing: border-box; line-height: 26px; margin-left: 21px;">
<h4 style="box-sizing: border-box; font-family: roboto, sans-serif; color: #111111; font-weight: 400; margin: 24px 0px 14px; font-size: 19px; line-height: 29px;"><span style="box-sizing: border-box; font-weight: bold;">Falta real de esfuerzo:</span></h4>
</li>
</ul>
<p style="box-sizing: border-box; line-height: 26px; margin-top: 0px; margin-bottom: 26px; word-wrap: break-word;"><span style="box-sizing: border-box;">Si antes de entrar en crossfit eras una persona deportista, los primeros meses suelen ser la ca&ntilde;a. No necesitas esforzarte tanto para aprender los movimientos b&aacute;sicos porque &ldquo;de la nada&rdquo; te salen, o no te supone mucho tiempo pillarlos. El problema llega cuando ya vas pesado en snatch o cuando debes hacer un complex de movimientos gimn&aacute;sticos avanzados. Te sorprendes ante un nivel de dificultad al que no est&aacute;s acostumbrado y eso puede provocar un bloqueo al no saber afrontar la situaci&oacute;n.</span></p>
<p style="box-sizing: border-box; line-height: 26px; margin-top: 0px; margin-bottom: 26px; word-wrap: break-word;"><span style="box-sizing: border-box;">Se pueden dar uno o varios motivos a la vez, pero las consecuencias siempre van a ser las mismas:</span></p>
<ol style="box-sizing: border-box; padding: 0px; margin-bottom: 26px;">
<li style="box-sizing: border-box; line-height: 26px; margin-left: 21px;"><span style="box-sizing: border-box; font-weight: bold;">A nivel de pensamiento</span><span style="box-sizing: border-box;">: al pensar que no podemos, que ser&aacute; imposible conseguirlo.</span></li>
<li style="box-sizing: border-box; line-height: 26px; margin-left: 21px;"><span style="box-sizing: border-box; font-weight: bold;">A nivel de emoci&oacute;n</span><span style="box-sizing: border-box;">: surgen emociones que catalogamos como negativas: miedo, frustraci&oacute;n, tristeza, ira&hellip; A largo plazo pueden derivar en depresi&oacute;n, desesperanza, baja autoestima y problemas de aprendizaje. Adem&aacute;s, desarrollamos una actitud victimista y pesimista ante el problema, como si no dependiera de nosotros hacerlo posible.</span></li>
<li style="box-sizing: border-box; line-height: 26px; margin-left: 21px;"><span style="box-sizing: border-box; font-weight: bold;">A nivel de acci&oacute;n y resultado</span><span style="box-sizing: border-box;">: si decidimos no poner soluci&oacute;n, directamente dejaremos de intentarlo y optaremos siempre por las opciones escaladas, lo que definitivamente implica como resultado que no mejoraremos nunca. Incluso puede que, llegado cierto nivel de desmotivaci&oacute;n, decidamos abandonar el box.</span></li>
</ol>
<p style="box-sizing: border-box; line-height: 26px; margin-top: 0px; margin-bottom: 26px; word-wrap: break-word;"><span style="box-sizing: border-box; font-weight: bold;">Conclusiones: la oportunidad oculta.</span></p>
<p style="box-sizing: border-box; line-height: 26px; margin-top: 0px; margin-bottom: 26px; word-wrap: break-word;"><span style="box-sizing: border-box;">En este art&iacute;culo os he presentado un problema que es tan cotidiano como el hecho de calentar antes de entrenar:&nbsp;</span><span style="box-sizing: border-box; font-weight: bold;">cuando no conseguimos realizar el ejercicio que nos exigen</span><span style="box-sizing: border-box;">. En primer lugar, os habl&eacute; de las dos razones por las que esto ocurre: por cuestiones meramente f&iacute;sicas o como resultado de un bloqueo mental. En segundo lugar, he profundizado en este concepto de bloqueo mental, exponiendo su definici&oacute;n, las causas posibles de su aparici&oacute;n y las consecuencias que generan si no buscamos soluciones.</span></p>
<p style="box-sizing: border-box; line-height: 26px; margin-top: 0px; margin-bottom: 26px; word-wrap: break-word;"><span style="box-sizing: border-box; font-weight: bold;">Aunque vivir un bloqueo mental no sea una experiencia agradable para nadie, la verdad es que detr&aacute;s de &eacute;l se esconde una oportunidad de aprendizaje &uacute;nica.&nbsp;</span><span style="box-sizing: border-box;">Primeramente, porque te ayuda a conocerte m&aacute;s a fondo y saber en qu&eacute; punto est&aacute;s con respecto a tu avance en este deporte. En segundo lugar, porque las emociones est&aacute;n hechas para informarnos y protegernos de lo que ocurre o puede ocurrir a nuestro alrededor y escucharlas con atenci&oacute;n puede ayudarnos a encontrar una soluci&oacute;n ajustada y eficaz, convirti&eacute;ndolas en nuestras mayores aliadas.</span></p>
<p style="box-sizing: border-box; line-height: 26px; margin-top: 0px; margin-bottom: 26px; word-wrap: break-word;">&nbsp;</p>
</div>',
  'image' => 'posts/August2018/S8CCKUW3QhM9b66ddeTG.jpg',
  'slug' => 'los-bloqueos-por-que-no-avanzamos',
  'meta-description' => 'Meta Description for sample post',
  'meta-keywords' => 'keyword1, keyword2, keyword3',
  'status' => 'PUBLISHED',
  'featured' => 0,
          ],
        ];
        post::insert($posts);
    }
}
